//! Manual hipBLAS FFI bindings (not generated by bindgen)

#![allow(non_camel_case_types, non_snake_case, dead_code)]

pub type hipblasHandle_t = *mut std::ffi::c_void;
pub type hipblasStatus_t = i32;
pub type hipblasOperation_t = i32;

pub const HIPBLAS_OP_N: hipblasOperation_t = 111;  // No transpose
pub const HIPBLAS_OP_T: hipblasOperation_t = 112;  // Transpose
pub const HIPBLAS_OP_C: hipblasOperation_t = 113;  // Conjugate transpose

pub const HIPBLAS_STATUS_SUCCESS: hipblasStatus_t = 0;

extern "C" {
    pub fn hipblasCreate(handle: *mut hipblasHandle_t) -> hipblasStatus_t;
    pub fn hipblasDestroy(handle: hipblasHandle_t) -> hipblasStatus_t;
    
    pub fn hipblasHgemm(
        handle: hipblasHandle_t,
        transa: hipblasOperation_t,
        transb: hipblasOperation_t,
        m: i32, n: i32, k: i32,
        alpha: *const half::f16,
        a: *const half::f16, lda: i32,
        b: *const half::f16, ldb: i32,
        beta: *const half::f16,
        c: *mut half::f16, ldc: i32,
    ) -> hipblasStatus_t;
    
    pub fn hipblasSgemm(
        handle: hipblasHandle_t,
        transa: hipblasOperation_t,
        transb: hipblasOperation_t,
        m: i32, n: i32, k: i32,
        alpha: *const f32,
        a: *const f32, lda: i32,
        b: *const f32, ldb: i32,
        beta: *const f32,
        c: *mut f32, ldc: i32,
    ) -> hipblasStatus_t;
}
